### ISSUE TITLE
on(:local) fails on windows

### ISSUE THREAD

**Issue by jarredholman** [capistrano/sshkit#252]
Etc.getpwuid returns nil on windows so SSHKit::Host.new(:local) raises an exception

**Comment by leehambley** [comment]
Don't use `on(:local)` there's no good reason not to use the standard Ruby/Rake APIs. It exists for legacy reasons, if it doesn't work on your platform please provide a patch if you can.

**Comment by leehambley** [comment]
http://stackoverflow.com/a/3544741/119669 might give you a place to start.

**Comment by jarredholman** [comment]
Well I am using `run_locally` in capistrano and this bug is preventing me from updating to the latest version.
I guess I'll try to avoid using that.

**Comment by leehambley** [comment]
There's literally nothing to be gained by using `run_locally()`, if you're on Windows and something is unsupported, you can monkey patch it anyway, the SO link shows some ways you might work around that rather than refactoring your code. `run_locally` is basically no different to shelling out with Ruby http://julialang.org/blog/2012/03/shelling-out-sucks/ unless you are using the command map, and plugins, etc which essentially don't do anything locally anyway.

**Comment by mattbrictson** [comment]
I think this has been fixed by #293
