### ISSUE TITLE
sh -c without sudo?

### ISSUE THREAD

**Issue by myfreeweb** [capistrano/sshkit#259]
Thing that just happened on a real project: the system administrator `chsh`'d the app user account to `csh` and I forgot the root password... so once again capistrano broke, because it assumes POSIX shell.

I had to monkey patch right in the `deploy.rb`:

```ruby
SSHKit::Command.class_eval do
  alias :to_command2 :to_command
  def to_command
    "sh -c '#{to_command2}'"
  end
end
```

This is just a terrible hack. Please add real support for wrapping commands in `sh -c` (or any shell's `-c` really).

**Comment by leehambley** [comment]
> because it assumes POSIX shell.

Actually it *requires* one, we've obviously lost that from the docs at some point. I'll make sure to fix it.

The decision to drop the `shell -c '…'` option was taken because the interactions between login, and non-login shells, and the assignment (or not) of a pty to grant an interactive shell were compounded by people mixing those options with shell flags.

Remember this is Ruby, `alias` is a perfectly valid approach, and you are obviously fortunate to know how to work around it, and to understand why you would want to.

**Comment by myfreeweb** [comment]
What about launching a shell? I don't know about Ruby's netssh, but in OpenSSH you can do `ssh -t some@where zsh` and it will launch zsh.

**Comment by leehambley** [comment]
Ignore the page title - http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/ this page explains some of the background. We don't *want* a shell with a tty 99% of the time.
