### ISSUE TITLE
Do not show "Failed" in red for checks which are used in conditionals

### ISSUE THREAD

**Issue by will-in-wi** [capistrano/sshkit#287]
I support Capistrano usage in-house and recently on Stack Overflow, and I've discovered that one of the main things which trips people up is the fact that checks for file/folder/symlink existence display Failed in red when the file/folder/symlink doesn't exist yet. However, these checks are just to see whether Capistrano needs to create the object, and represent normal usage.

Could we do something to clean up this UX issue?

My thought is to add a parameter to `SSHKit::Command` called `boolean?` or `check?` which would cause the formatter to either show Failed in green, or possibly display "Returned non-0" in green, or something like that.

Does this make sense? Does this solution make sense? I'd be willing to work on it, but didn't want to start without at least a tentative blessing.

Thanks!

**Comment by mattbrictson** [comment]
Perhaps the formatter could check `command.options[:raise_on_non_zero_exit]`? You could add a `Command#raise_on_non_zero_exit?` convenience method to make for a cleaner API.

Anyway, I do like your suggestion, but I think this issue you identified is just the tip of the iceberg. The default formatter uses red whenever there is stderr output. Some commands emit stderr even when nothing has gone wrong (I believe `rake assets:precompile` does this?). Is there a way to colorize the output that won't be misleading?

**Comment by mattbrictson** [comment]
Alternatively, you could use a different formatter, like [Airbrussh](https://github.com/mattbrictson/airbrussh) (shameless plug).

**Comment by leehambley** [comment]
Well, I hear both arguments, but I tend to air on the side of education here, that this is the way terminals and shells work, the posix inherited fundamentals aren't going anywhere, and hiding them from people isn't going to help, because they won't learn anything.

Regarding badly behaved programmes (`rake assets:precompile` I don't know about) there are tonnes, `Thor` and thus all the Rails generators, and everything else based on it never exit with a status other than `0` because their CLI testing framework can't handle programs that *fail* which is simply insane.

Btw, gotta say it @mattbrictson 's Airbrussh is pretty neat, hey @mattbrictson weren't we going to merge SSHKit and Airbrussh, I kinda forgot how we left that topic? (pick me up out of band about that if you like)

**Comment by will-in-wi** [comment]
Airbrussh looks really cool! I'm going to try it out on some of my projects.

I agree with the point on education, I agree that I'd really rather not work around badly designed applications by doing something other than what POSIX does. For example, I'd probably leave stderr colored red. However, I don't think it is unusual to use the return code as an indicator of true/false, so that might be worth some clarity.

If you merge Airbrussh, that might fix it for me right there. Anyway, just a thought, feel free to close if you want.

Thanks!

**Comment by leehambley** [comment]
Cheers, I'll close the issue, but don't take that as me snubbing you, I'm right on the fence with the red "failed", had you caught me on another day I might have changed it, but I'm going to leave it be for now. And think about suppressing the whole directory checks, anyway.
