### ISSUE TITLE
bundle install fails when installing ffi

### ISSUE THREAD

**Issue by mkunkel** [capistrano/sshkit#314]
I'm using `capistrano-bundler`, `capistrano-rails`, and `capistrano-rvm`. Deploys had been working successfully until recently.

Deploys now result in the following error:

```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@redacted: bundle exit status: 5
bundle stdout: An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.
bundle stderr: Nothing written

SSHKit::Command::Failed: bundle exit status: 5
bundle stdout: An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.
bundle stderr: Nothing written

Tasks: TOP => deploy:updated => bundler:install
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@redacted: bundle exit status: 5
bundle stdout: An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.
bundle stderr: Nothing written
```

After logging in as the deploy user, I executed `gem install ffi -v '1.9.10'` which completed successfully. The deploy still results in the same error. I've also verified that both attempts have been using Ruby 2.2.2p95

**Comment by mattbrictson** [comment]
Hi, this is a general gem installation/Bundler problem and not an SSHKit issue, and I think you'd have better luck reporting this on Stack Overflow where more eyes will see it.

My 2¢: Your successful `gem install` when logging in to the shell does not fix the deploy because `gem install` and `bundle` install their gems in different places. However what this shows is  that `ffi` can be installed in your interactive shell, but not during a non-interactive deploy.

I suggest checking:

* Can you run `bundle` successfully in an interactive shell, i.e. inside the most recent release directory? (This may fix your deploy for the time being.)
* Are there any environment variables (e.g. `$PATH`) being set in your interactive shell that aren't present during a deploy?
* What is the full error from Bundler? (You may need to upgrade to the latest SSHKit to get more of output.)


--

GitHub issues is for feature requests or bug reports. Since this is more of a how-to question, I am closing this issue. The Capistrano team recommends you use [Stack Overflow](http://stackoverflow.com/questions/tagged/capistrano) for general questions. For more details, please see our [contribution policy](https://github.com/capistrano/capistrano/blob/master/CONTRIBUTING.md).

**Comment by mattbrictson** [comment]
Also relavant, from the FAQ: [Why does something work in my SSH session, but not in Capistrano?](http://capistranorb.com/documentation/faq/why-does-something-work-in-my-ssh-session-but-not-in-capistrano/)
