### ISSUE TITLE
Can't use it with ProxyJump in config

### ISSUE THREAD

**Issue by rosenfeld** [capistrano/sshkit#367]
When I try to use ProxyJump in `.ssh/config` the command gets stucked and will never return. I'm currently forced to use ProxyCommand instead with `ssh -i deploy_key root@jump-host -W %h:%p`. Even if the IdentityKey is specified in .ssh/config I have to use `-i` anyway. Any ideas why `ProxyJump jump-host:22` is getting stuck?

**Comment by rosenfeld** [comment]
I forgot to mention that the ProxyJump option works with an external ssh client, by using `ssh -F .ssh/config target-host`. But for some reasons the commands never return when using through SSHKit...

**Comment by mattbrictson** [comment]
Hi, thanks for the report!

SSHKit relies on Net::SSH to parse the `.ssh/config` file and take appropriate action based on the settings therein. You can see the code here:

https://github.com/net-ssh/net-ssh/blob/81170de0b08a47f1f86001ea5ab7f519da29c00f/lib/net/ssh/config.rb

I am not familiar with `ProxyJump`, but based on some quick research it seems to be a brand new feature of ssh that was [just released earlier this month](http://www.phoronix.com/scan.php?page=news_item&px=OpenSSH-7.3-Released). It is not surprising that Net::SSH doesn't support it yet.

I suggest opening an issue in the [Net::SSH repository](https://github.com/net-ssh/net-ssh/issues) requesting `ProxyJump` support. I believe the project is in maintenance mode and therefore this might be a long shot, but perhaps an interested contributor will take up the challenge.

Since this is a Net::SSH issue and not something we can fix or work around in SSHKit, I will mark this as closed. If I've misunderstood the issue, please re-open it.

**Comment by rosenfeld** [comment]
Thanks, I had not realized previously that net-ssh actually implemented the SSH protocol in Ruby, I thought it would be just a wrapper over the `ssh` command. I'll create an issue there, thanks!

**Comment by rosenfeld** [comment]
Created the issue here: https://github.com/net-ssh/net-ssh/issues/430
