### ISSUE TITLE
Project local .ssh/config isn't read

### ISSUE THREAD

**Issue by loaighoraba** [capistrano/sshkit#462]
I have a local .ssh/config file in my project, but when deploying with capistrano the file is not read at all, so what to do so that these options get merged in?

**Comment by will-in-wi** [comment]
It looks like this feature was introduced in SSHKit 1.2.0. https://github.com/capistrano/sshkit/pull/26

We use GitHub for bug reports and feature requests, and we use Stackoverflow for support requests. If you think this is a bug, could you provide enough information to reproduce the issue? Ideally, a repo with a simple capistrano configuration which replicates the issue. Otherwise, a Gist with the failing configuration would help.

**Comment by loaighoraba** [comment]
thanks @will-in-wi 

it seems it was my mistake, I thought that configuration file will be used automatically, however when supplying the options manually it worked

`server "example.com", user: "user", roles: %w{web app }, ssh_options: Net::SSH.configuration_for("example", true)`


I wonder if the configurations can be read implicitly.

**Comment by will-in-wi** [comment]
I'm glad you got it figured out!
