### ISSUE TITLE
Dependency Issue in i18n with the latest version of sshkit

### ISSUE THREAD

**Issue by ranjith-juhomi** [capistrano/sshkit#521]
Team,

We have recently upgraded our application software, incorporating the latest gem versions. During this upgrade, we migrated the sshkit gem to its most recent version. However, upon utilizing the gem, we encountered the following error. After a thorough analysis of the error message, it appears that the dependent gem 'i18n' within sshkit is causing the issue. 

Error Description: 
#<Thread:0x00007fc5a823cda8 /home/vagrant/.rvm/gems/ruby-3.2.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
/home/vagrant/.rvm/gems/ruby-3.2.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing wrong number of arguments (given 2, expected 0..1) (SSHKit::Runner::ExecuteError)
        from /home/vagrant/.rvm/gems/ruby-3.2.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/home/vagrant/.rvm/gems/ruby-3.2.0/gems/i18n-1.14.0/lib/i18n.rb:210:in `translate': wrong number of arguments (given 2, expected 0..1) (ArgumentError)

**Comment by mattbrictson** [comment]
@ranjith-juhomi thanks for the report.

My intuition is that this is not an sshkit issue, because sshkit does not use the i18n gem directly.

Are you using sshkit via capistrano? If so, there was a bug similar to this (https://github.com/capistrano/capistrano/issues/2091) was reported and fixed in capistrano 3.14.1. If you are using capistrano, please confirm you are using version 3.14.1 or newer.

Otherwise, I think I will need a more detailed backtrace to troubleshoot the issue. The exception is being raised in the `i18n` gem, but it is not clear what code is calling i18n. The `sshkit/runners/parallel.rb:11` in the error message is simply wrapping the underlying exception and is not the actual cause:

https://github.com/capistrano/sshkit/blob/3555a98d5c61e26472e988b62601fd323b374176/lib/sshkit/runners/parallel.rb#L15

 If you could add `--trace` (if using rake) or if you have more insight into what code is being used on top of sshkit, that would help.

**Comment by ranjith-juhomi** [comment]
Thanks [mattbrictson](https://github.com/mattbrictson), it works after upgrading Capistrano to 3.14.1. It's a great help. Thank you so much.
