### ISSUE TITLE
Feature: Add a DEBUG/INFO note to the log when execute() is passed arguments that won't be mapped.

### ISSUE THREAD

**Issue by seenmyfate** [capistrano/sshkit#78]
[Originally raised on Cap issues](https://github.com/capistrano/capistrano/issues/800)

**Comment by leehambley** [comment]
Explanation: this was supposed to be so that option hashes passed with bogus keys would result in a warning. When @seenmyfate and I wrote that issue at Capistrano Ruby 2.x with keyword arguments wasn't a think, and I don't think that [strong_params](https://github.com/rails/strong_parameters) even existed, maybe one of those two new things gives us something to work with?

**Comment by mattbrictson** [comment]
I've never come across a case where an options hash was passed to `execute` (although looking at the code, I see that it's possible), so I'm not sure what confusion/problems people are having with this.

Also, since backends are pluggable, it is possible that different backends will have different requirements/expectations for execute options, which makes it hard to enforce a standard policy.

**Comment by leehambley** [comment]
Agreed
